create table ADMIN (
	Id integer not null, 
	Username varchar(50) not null, 
	Birthdate date not null, 
	Education clob not null, 
	Experience clob not null, 
	Languages clob not null, 
	Skills clob not null, 
	Email varchar(255) not null, 
	Facebook varchar(255), 
	Gender varchar(6) not null, 
	HireDate date, 
	Name varchar(50) not null, 
	Password varchar(20) not null, 
	Phone varchar(255) not null, 
	JobId integer not null, 
	Permissions integer, 
	primary key (Id, Username)
);

create table Worker (
	Id integer not null, 
	Username varchar(50) not null, 
	Birthdate date not null, 
	Education clob not null, 
	Experience clob not null, 
	Languages clob not null, 
	Skills clob not null, 
	Email varchar(255) not null, 
	Facebook varchar(255), 
	Gender varchar(255) not null, 
	HireDate date, 
	Name varchar(50) not null, 
	Password varchar(20) not null, 
	Phone varchar(255) not null, 
	JobId integer not null, 
	primary key (Id, Username)
);

create table USER_SESSION (
	SessionId varchar(256) not null, 
	ClientIp varchar(19), 
	DeviceKey varchar(255), 
	EndTime timestamp not null, 
	StartTime timestamp not null, 
	EmployeId integer not null, 
	EmployeName varchar(50) not null, 
	primary key (SessionId)
);

create table JOB (
	Id integer generated by default as identity, 
	Description clob, 
	Hours integer, 
	Paycheck float not null, 
	Rank integer, 
	Title varchar(50) not null, 
	primary key (Id)
);

create table TAG (
	Id varchar(10) not null, 
	Background bigint not null, 
	Description varchar(50) not null, 
	Foreground bigint not null, 
	primary key (Id)
);

create table UNIT (
	Id varchar(2) not null, 
	Description varchar(50) not null, 
	primary key (Id)
);

create table BASE_CURRENCY (
	CurrencyType varchar(20) not null, 
	Id varchar(3) not null, 
	Name varchar(20) not null,
	ConvFactor float, 
	primary key (Id)
);

create table CATEGORY (
	Id varchar(10) not null, 
	Description varchar(50) not null, 
	primary key (Id)
);

create table CONTACT (
	Id integer not null, 
	ConvFactor integer, 
	Name varchar(50) not null, 
	Priority varchar(255), 
	primary key (Id)
);

create table CONTACT_TAG (
	ContactId integer not null, 
	TagId varchar(10) not null
);

create table DOC_ORDER (
	Id varchar(50) not null, 
	CreationDate timestamp, 
	Discount float, 
	Number integer, 
	Total float, 
	LastChangeDate timestamp, 
	ContactId integer not null, 
	CurrencyId varchar(3) not null, 
	DocStatusId varchar(1) not null, 
	EmployeeId integer not null, 
	EmployeeName varchar(50) not null, 
	primary key (Id)
);

create table DOC_STATUS (
	Id varchar(1) not null, 
	Description varchar(50) not null, 
	primary key (Id)
);

create table ORDER_ROW (
	Id varchar(50) not null, 
	Discount float, 
	Quantity float, 
	Total float, 
	CurrencyId varchar(3) not null, 
	ItemId integer not null, 
	OrderId varchar(50) not null, 
	UnitId varchar(2), primary key (Id)
);

create table ITEM (
	Id integer not null, 
	Description varchar(255) not null, 
	Discount float, 
	Price float not null, 
	Title varchar(50) not null, 
	CategoryId varchar(10) not null, 
	CurrencyId varchar(3) not null, 
	UnitId varchar(2), 
	primary key (Id)
);

create table ITEM_TAG (
	ItemId integer not null, 
	TagId varchar(10) not null
);


alter table ADMIN add constraint FK_kh1knavww1fm4pwu501exnyco foreign key (JobId) references JOB;
alter table Worker add constraint FK_sm4x9k292rtsavb25sq0jt1dl foreign key (JobId) references JOB;
alter table CONTACT_TAG add constraint FK_m824m7e8wpxhn7ddomg6n0rrw foreign key (TagId) references TAG;
alter table CONTACT_TAG add constraint FK_jyi1jbndxw611gn56aa7c33vd foreign key (ContactId) references CONTACT;
alter table ITEM add constraint FK_kil5dy5mp7a869720gwmk12v9 foreign key (CategoryId) references CATEGORY;
alter table ITEM add constraint FK_mwnlbqys7sarh2u3igr0nhh6w foreign key (CurrencyId) references BASE_CURRENCY;
alter table ITEM add constraint FK_fp7mxw065a1bnurc803hp0ff9 foreign key (UnitId) references UNIT;
alter table ITEM_TAG add constraint FK_p8co0kxj5a5p6921q6gc9aj7y foreign key (TagId) references TAG;
alter table ITEM_TAG add constraint FK_kao928mlwm5c7386vigxui0ya foreign key (ItemId) references ITEM;
alter table DOC_ORDER add constraint FK_n52cxm1jco5er50fmc44h7g1 foreign key (ContactId) references CONTACT;
alter table DOC_ORDER add constraint FK_dcdv4kr7igmnghg1n96ygq6vh foreign key (CurrencyId) references BASE_CURRENCY;
alter table DOC_ORDER add constraint FK_bql51he8fiobh7e2137x0ymq6 foreign key (DocStatusId) references DOC_STATUS;
alter table ORDER_ROW add constraint FK_8hxb9j307axvshbxiktfur7v foreign key (CurrencyId) references BASE_CURRENCY;
alter table ORDER_ROW add constraint FK_cmncsle38y8iertgp6dvyvb90 foreign key (ItemId) references ITEM;
alter table ORDER_ROW add constraint FK_4fytv8adamblcnav3rybeopjb foreign key (OrderId) references DOC_ORDER;
alter table ORDER_ROW add constraint FK_24ktf1cyttwjg5jj5unqbcv9o foreign key (UnitId) references UNIT;